Update bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -17,16 +17,17 @@ stages:
 workflows:
   RN-Android:
     steps:
+    - avd-manager@1:
+        inputs:
+        - emulator_id: Pixel2API30
+        - create_command_flags: "--sdcard 2048M"
+        - api_level: '28'
+    - wait-for-android-emulator@1:
+        inputs:
+        - boot_timeout: '800'
     - activate-ssh-key@4.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@6.2: {}
-    - avd-manager@1.2:
-        inputs:
-        - emulator_id: Pixel2API30
-        - api_level: '28'
-    - wait-for-android-emulator@1.0:
-        inputs:
-        - boot_timeout: '600'
     - npm@1.1:
         inputs:
         - command: install
@@ -43,6 +44,19 @@ workflows:
             #npm install -g react-native-cli
 
             npm install -g detox-cli
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            # write your script here
+            npx react-native run-android
     - script@1.2:
         inputs:
         - content: |-
@@ -54,6 +68,19 @@ workflows:
 
             detox build -c android.emu.debug
         title: Detox Build Android
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            # write your script here
+            npm rebuild detox
     - script@1.2:
         title: Detox E2E Android Test
         inputs:
@@ -64,7 +91,7 @@ workflows:
             # debug log
             set -x
 
-            detox test --configuration android.emu.debug --cleanup --record-logs all --record-videos all --take-screenshots all --loglevel trace
+            detox test -c android.emu.debug --record-logs all --take-screenshots all --record-videos all --force-adb-install
     - script@1.2:
         inputs:
         - content: |-
